### ISSUE TITLE
Search in Alfresco returns error referencing Slingshot

### ISSUE THREAD

**Issue by DBlamire** [Open-MBEE/mms-alfresco#70] opened 2017-06-26 20:09 UTC
The current setup that the server is using.
Centos 6
Tomcat 7.0.78
Alfresco Community 5.0.d
ActiveMQ 5.14.5
Elasticsearch 5.4.1
PostgresQL-9.3

Attempted to do search in Alfresco which resulted in the following ERROR 

Created a site and uploaded 2 image files
![19496009_10155354445865502_295378728_o](https://user-images.githubusercontent.com/15755774/27557894-469731f6-5a89-11e7-9cef-28976510514e.jpg)

Ran search for Image files, which autoloaded result successfully
![19532887_10155354445545502_902930690_o](https://user-images.githubusercontent.com/15755774/27557899-4e041b20-5a89-11e7-9683-92eb52233328.jpg)

Received error
![19549506_10155354445380502_902200975_o](https://user-images.githubusercontent.com/15755774/27557902-52ce68ea-5a89-11e7-9620-eb069927486a.jpg)

Error from logs:

2017-06-26 15:57:41,483  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-6] Exception from executeScript - redirecting to status template error: 05260006 Wrapped Exception (with status template): 05260026 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js': 05260025 TypeError: The processing instruction target matching "[xX][mM][lL]" is not allowed. (classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js#1038)
 org.springframework.extensions.webscripts.WebScriptException: 05260006 Wrapped Exception (with status template): 05260026 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js': 05260025 TypeError: The processing instruction target matching "[xX][mM][lL]" is not allowed. (classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js#1038)
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1127)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:482)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:551)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.scripts.ScriptException: 05260026 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js': 05260025 TypeError: The processing instruction target matching "[xX][mM][lL]" is not allowed. (classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js#1038)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:204)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:212)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:174)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:102)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1364)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 34 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 05260025 TypeError: The processing instruction target matching "[xX][mM][lL]" is not allowed. (classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js#1038)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:526)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:200)
	... 39 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: The processing instruction target matching "[xX][mM][lL]" is not allowed. (classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js#1038)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3677)
	at org.mozilla.javascript.xmlimpl.XmlProcessor$RhinoSAXErrorHandler.throwError(XmlProcessor.java:56)
	at org.mozilla.javascript.xmlimpl.XmlProcessor$RhinoSAXErrorHandler.fatalError(XmlProcessor.java:65)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanPIData(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanPIData(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanPI(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.mozilla.javascript.xmlimpl.XmlProcessor.toXml(XmlProcessor.java:225)
	at org.mozilla.javascript.xmlimpl.XmlNode.createElement(XmlNode.java:87)
	at org.mozilla.javascript.xmlimpl.XMLLibImpl.parse(XMLLibImpl.java:416)
	at org.mozilla.javascript.xmlimpl.XMLLibImpl.ecmaToXml(XMLLibImpl.java:452)
	at org.mozilla.javascript.xmlimpl.XMLObjectImpl.ecmaToXml(XMLObjectImpl.java:822)
	at org.mozilla.javascript.xmlimpl.XML.jsConstructor(XML.java:186)
	at org.mozilla.javascript.xmlimpl.XMLObjectImpl.execIdCall(XMLObjectImpl.java:610)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:343)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2349)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6._c_getQueryTemplate_21(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js:1038)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.call(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6._c_getSearchResults_20(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js:1011)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.call(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6._c_main_22(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js:1069)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.call(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6._c_script_0(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js:1072)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.call(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.call(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_slingshot_search_search_get_js_6.exec(classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:502)
	... 40 more

**Comment by HuiJun** [comment] 2017-06-27 17:18
I was able to replicate the error, but more research on the issue is required.

**Comment by EDKarlsson** [comment] 2017-07-12 21:14
Fixed with PR 86

**Closed as completed by EDKarlsson** 2017-07-12 21:14 UTC
