### ISSUE TITLE
Working with maven cli behind a proxy

### ISSUE THREAD

**Issue by borromeotlhs** [Open-MBEE/mms-alfresco#153] opened 2017-09-14 15:14 UTC
The settings, as-is, won't work for maven even if you set the proxy server in settings.xml.

This leaves having to set the vars from your cli, a la https://github.com/rimerosolutions/maven-wrapper-example/issues/2 .

I think documentation should be updated for settings the proxies for each tool that is required to get mms all-in-one running.

**Comment by HuiJun** [comment] 2017-10-09 22:29
Unfortunately, we don't have any way to test this right now. Do you know if this only applies to Windows?

**Comment by HuiJun** [comment] 2018-07-09 16:55
Closing issue. Please open a new issue if this is still a problem.

**Closed as completed by HuiJun** 2018-07-09 16:55 UTC

**Comment by borromeotlhs** [comment] 2018-07-09 17:34
Holy cow!  What's the point of metrics if you close stale tickets?  I
barely got a chance to respond to your question, that has been largely
ignored, before you close it?
No, this isn't just windows.
I also gave the solution in the ticket, so unless you've implemented what
I've asked for OR made an alternative fix, I don't see the justification
for closing this.

Again, if your doing it to drive down metrics because the employer wants
progress, then don't bother.  Your tool isn't ready for primetime if simple
observations regarding issues are summarily ignored.  I feel like I'm on
twitter trying to reason with people here!  Am I crazy?

Please explain the rationale for why you think it's OK to close this, and
waste MY time that I invested in a good faith effort to FIX your product
FOR FREE, absent of actual discussion?!?

**Comment by HuiJun** [comment] 2018-07-09 20:52
If 10 months is not enough time for a ticket to be responded to, then I'm at a lose for words. The rationale is that it's been 10 months, and no updates, so it's safe to assume that the issue is resolved or abandoned. This is just a standard practice. It baffles me that you would question this.

The "solution" you gave was for a 5 year old issue on an abandoned fork of an abandoned maven wrapper version. If it worked for you, you're more than welcome to contribute the documentation back. This is open source software. There is no employer monitoring progress via github issues and people can contribute freely to the source code.

**Comment by borromeotlhs** [comment] 2018-07-10 02:30
Then just close it.  I am more than capable of updating the MOST recent
stuff, but I'd need dialogue first.  But, again, you closed it. Which
baffles me why you care so much that you think I'd want to invest more time
when apparently, I'm the one that tracks your progress?  I just used one
branch as that is what your documentation points everyone to.  Don't be
pissed at me for your documentations lack of clarity (something I'll gladly
help, if there were an OPEN issue).

So MMMM :P  Jk, but seriously, I asked the question, got no response, and
assumed you'd all come back to it when you have time.  A perhaps more
optimal solution is to close, and then redirect me to a NEW ticket that
references closing a stale one, with at least some indication about what
you'd think I should or could do.

That all being said, what you wanna do about it? I can go troll mode and
not contribute as this is my personal time.  Or, you can be a little more
understanding that:
If it worked for you, you're more than welcome to contribute the
documentation back. This is open source software. There is no employer
monitoring progress via github issues and people can contribute freely to
the source code.
